# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trt_plugin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10trt_plugin.proto\x12\x13macnica_trt_plugins\"\x9c\x01\n\x0fpooling_Message\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x03\x12.\n\x04mode\x18\x02 \x01(\x0e\x32 .macnica_trt_plugins.PoolingMode\x12\x0e\n\x06window\x18\x03 \x03(\x03\x12\x0e\n\x06stride\x18\x04 \x03(\x03\x12+\n\x04impl\x18\x05 \x01(\x0e\x32\x1d.macnica_trt_plugins.AlgoImpl\"\x1c\n\x0c\x63opy_Message\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x03*?\n\x0f\x44\x61taTypeMessage\x12\n\n\x06kFloat\x10\x00\x12\t\n\x05kHalf\x10\x01\x12\t\n\x05kInt8\x10\x02\x12\n\n\x06kInt32\x10\x03*\'\n\x0bPoolingMode\x12\x0b\n\x07Maximum\x10\x00\x12\x0b\n\x07\x41verage\x10\x01*\x1f\n\x08\x41lgoImpl\x12\x08\n\x04\x43UDA\x10\x00\x12\t\n\x05\x43uDNN\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trt_plugin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPEMESSAGE._serialized_start=230
  _DATATYPEMESSAGE._serialized_end=293
  _POOLINGMODE._serialized_start=295
  _POOLINGMODE._serialized_end=334
  _ALGOIMPL._serialized_start=336
  _ALGOIMPL._serialized_end=367
  _POOLING_MESSAGE._serialized_start=42
  _POOLING_MESSAGE._serialized_end=198
  _COPY_MESSAGE._serialized_start=200
  _COPY_MESSAGE._serialized_end=228
# @@protoc_insertion_point(module_scope)
